name: Build and deploy cheerz-devops-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build app with Gradle
        run: ./gradlew build

      - name: Extract JAR contents for Docker layering
        run: |
          mkdir -p build/dependency
          cd build/dependency
          jar -xf ../libs/cheerz-devops-test-*-SNAPSHOT.jar

      - name: Build Docker image
        run: docker build -t cheerz-devops-test:latest .
